name: Validate and Encode

on:
  push:
    branches:
      - main   # 当 main 分支有提交时运行
  pull_request:
    branches:
      - main   # PR 时也会运行
  workflow_dispatch:  # 支持手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install base58

      - name: Run validation and encoding
        run: |
          python validate_and_encode.py
